fix: php 8.2 deprecated
humanmade/Cavalcade-Runner pull request #73
Opened 2024-02-22 08:57 UTC by devhaozi

2024-02-27 16:27 UTC, rmccue requested changes

2024-02-27 16:27 UTC, rmccue commented on inc/class-logger.php
> +	protected $table_prefix;
These seem to be accidentally duplicated?

```suggestion
```

2024-03-24 08:50 UTC, devhaozi commented
@rmccue Could you help to review this pr?

2024-04-29 10:00 UTC, mikelittle approved these changes
Looks good now. Thanks for this.

2024-04-29 10:00 UTC, merged